/*
 * Chart of accounts transcribed from the supplied K.Y.S. March 2026 reports.
 * A few handwritten/blurred bank reference suffixes have intentionally been
 * shortened; the account code and account purpose are retained for the system.
 */
window.KYS_ACCOUNTS = [
  { code: "099", name: "Cash Book – General Cash", category: "asset", side: "Debit", visibility: "Standard", paymentMethod: "cash_book" },
  { code: "100", name: "Petty Cash", category: "asset", side: "Debit", visibility: "Standard" },
  { code: "101", name: "Capital Reserves", category: "equity", side: "Credit", visibility: "Confidential" },
  { code: "201", name: "Bank Interest Received", category: "other_income", side: "Credit", visibility: "Standard" },
  { code: "202", name: "People's Bank – Main Account", category: "asset", side: "Debit", visibility: "Standard", paymentMethod: "bank" },
  { code: "203", name: "People's Bank – Current A/C 010-1002-8", category: "asset", side: "Debit", visibility: "Standard", paymentMethod: "bank" },
  { code: "204", name: "People's Bank – Current A/C 010-1001-9", category: "asset", side: "Debit", visibility: "Standard", paymentMethod: "bank" },
  { code: "205", name: "People's Bank – Current A/C 010-1003-7", category: "asset", side: "Debit", visibility: "Standard", paymentMethod: "bank" },
  { code: "206", name: "Bank of Ceylon – Current A/C 007642826", category: "asset", side: "Debit", visibility: "Standard", paymentMethod: "bank" },
  { code: "208", name: "Seylan Bank – A/C 0260-13082861-001", category: "asset", side: "Debit", visibility: "Standard", paymentMethod: "bank" },
  { code: "209", name: "People's Bank – Savings A/C 010-2002-4", category: "asset", side: "Debit", visibility: "Standard", paymentMethod: "bank" },
  { code: "210", name: "People's Bank – Savings A/C 010-2001-9", category: "asset", side: "Debit", visibility: "Standard", paymentMethod: "bank" },
  { code: "211", name: "People's Bank – Savings A/C 010-2009-9", category: "asset", side: "Debit", visibility: "Standard", paymentMethod: "bank" },
  { code: "213", name: "Bank of Ceylon – Savings A/C 5117018", category: "asset", side: "Debit", visibility: "Standard", paymentMethod: "bank" },
  { code: "214", name: "Inter-bank Accounts Transfer Control", category: "liability", side: "Credit", visibility: "Admin only" },
  { code: "215", name: "K.Y.S. Pvt Ltd Control Account", category: "asset", side: "Debit", visibility: "Confidential" },
  { code: "216", name: "Lions Gate Security Service A/C", category: "asset", side: "Debit", visibility: "Standard" },
  { code: "217", name: "K.Y.S. Enterprise Current A/C", category: "asset", side: "Debit", visibility: "Confidential" },
  { code: "218", name: "K.Y.S. Pvt Ltd – People's Bank Savings A/C 010-2002-2005359", category: "asset", side: "Debit", visibility: "Confidential", paymentMethod: "bank", pvt: true },
  { code: "219", name: "K.Y.S. Pvt Ltd – DFCC Savings A/C 102004661424", category: "asset", side: "Debit", visibility: "Confidential", paymentMethod: "bank", pvt: true },
  { code: "220", name: "K.Y.S. Pvt Ltd – DFCC Current A/C 1010144378", category: "asset", side: "Debit", visibility: "Confidential", paymentMethod: "bank", pvt: true },
  { code: "221", name: "K.Y.S. Pvt Ltd – People's Bank Current A/C 010-1001-60053521", category: "asset", side: "Debit", visibility: "Confidential", paymentMethod: "bank", pvt: true },
  { code: "230", name: "K.Y.S. Pvt Ltd – Bank of Ceylon Current A/C 95334778", category: "asset", side: "Debit", visibility: "Confidential", paymentMethod: "bank", pvt: true },
  { code: "252", name: "People's Bank Loan – Account 010-8001-14102", category: "liability", side: "Credit", visibility: "Confidential" },
  { code: "253", name: "Seylan Bank LSD Facility", category: "liability", side: "Credit", visibility: "Confidential" },
  { code: "301", name: "DFCC Bank Loan A/C", category: "liability", side: "Credit", visibility: "Confidential" },
  { code: "302", name: "Motor Vehicles", category: "capital", side: "Debit", visibility: "Standard" },
  { code: "303", name: "F/A Lands", category: "capital", side: "Debit", visibility: "Standard" },
  { code: "304", name: "F/A Office Furniture", category: "capital", side: "Debit", visibility: "Standard" },
  { code: "305", name: "F/A Office Equipment", category: "capital", side: "Debit", visibility: "Standard" },
  { code: "306", name: "F/A General Maintenance Equipment", category: "capital", side: "Debit", visibility: "Standard" },
  { code: "307", name: "F/A Buildings", category: "capital", side: "Debit", visibility: "Standard" },
  { code: "308", name: "F/A Computer Software", category: "capital", side: "Debit", visibility: "Standard" },

  { code: "351", name: "Security Service Income", category: "trade_income", side: "Credit", visibility: "Standard" },
  { code: "352", name: "Cleaning Service Income", category: "trade_income", side: "Credit", visibility: "Standard" },
  { code: "353", name: "K.Y.S. Auto Service Rent Income", category: "other_income", side: "Credit", visibility: "Standard" },
  { code: "354", name: "Pinarawa Housing Complex Rent Income", category: "other_income", side: "Credit", visibility: "Standard" },
  { code: "355", name: "Welekade / Ratwatta Guest Rent Income", category: "other_income", side: "Credit", visibility: "Standard" },
  { code: "356", name: "2nd Mile Post Shop Complex / Chandrasiri House Rent Income", category: "other_income", side: "Credit", visibility: "Standard" },
  { code: "357", name: "MD Home Upper Stairs / Fruit Shop Rent Income", category: "other_income", side: "Credit", visibility: "Confidential" },
  { code: "358", name: "Haputhale Hotel Management Control A/C", category: "other_income", side: "Credit", visibility: "Standard" },
  { code: "359", name: "Haputhale Hotel Retained & Outstanding A/C", category: "asset", side: "Debit", visibility: "Standard" },
  { code: "360", name: "Geththama Textile Rent & Profit Income A/C", category: "other_income", side: "Credit", visibility: "Standard" },
  { code: "361", name: "Geththama Textile Rent & Profit O/S A/C", category: "asset", side: "Debit", visibility: "Standard" },
  { code: "362", name: "Rented Building Key Money Collection A/C", category: "other_income", side: "Credit", visibility: "Standard" },
  { code: "363", name: "Nilwala Hostel Income A/C", category: "other_income", side: "Credit", visibility: "Standard" },
  { code: "364", name: "Galaxy Hostel Income A&E A/C", category: "other_income", side: "Credit", visibility: "Standard" },
  { code: "365", name: "Pihillakade Housing Complex Rent Income O/S A/C", category: "other_income", side: "Credit", visibility: "Standard" },
  { code: "366", name: "Vineethagama House Rent Income A/C", category: "other_income", side: "Credit", visibility: "Standard" },

  { code: "401", name: "Creditors – Wijewardena Hardware", category: "liability", side: "Credit", visibility: "Standard" },
  { code: "402", name: "Creditors – National Hardware", category: "liability", side: "Credit", visibility: "Standard" },
  { code: "403", name: "Creditors – Weligama Hardware", category: "liability", side: "Credit", visibility: "Standard" },
  { code: "404", name: "Creditors – H.A. Bagasrawala & Sons", category: "liability", side: "Credit", visibility: "Standard" },
  { code: "405", name: "Creditors – Visvamis", category: "liability", side: "Credit", visibility: "Standard" },
  { code: "406", name: "Creditors – Demand Detergents", category: "liability", side: "Credit", visibility: "Standard" },
  { code: "407", name: "Creditors – DDJ Dias Lanka Filling Station", category: "liability", side: "Credit", visibility: "Standard" },
  { code: "408", name: "Creditors – ABT Garment", category: "liability", side: "Credit", visibility: "Standard" },
  { code: "409", name: "Creditors – Merends", category: "liability", side: "Credit", visibility: "Standard" },
  { code: "411", name: "Sundry Creditors A/C", category: "liability", side: "Credit", visibility: "Standard" },
  { code: "412", name: "External Borrowings A/C", category: "liability", side: "Credit", visibility: "Confidential" },
  { code: "414", name: "Creditors – Kabilaa Traders", category: "liability", side: "Credit", visibility: "Standard" },

  { code: "451", name: "Security & Cleaning Service Salary", category: "direct_expense", side: "Debit", visibility: "Standard" },
  { code: "452", name: "Security & Cleaning Service EPF 12%", category: "direct_expense", side: "Debit", visibility: "Standard" },
  { code: "453", name: "Security & Cleaning Service ETF 3%", category: "direct_expense", side: "Debit", visibility: "Standard" },
  { code: "451A", name: "Staff Salary Expenditure (Admin)", category: "operational_expense", side: "Debit", visibility: "Confidential" },
  { code: "452A", name: "Staff EPF 12% Expenditure (Admin)", category: "operational_expense", side: "Debit", visibility: "Confidential" },
  { code: "453A", name: "Staff ETF 3% Expenditure (Admin)", category: "operational_expense", side: "Debit", visibility: "Confidential" },
  { code: "454", name: "Staff Salary Advance A/C", category: "asset", side: "Debit", visibility: "Confidential" },
  { code: "455", name: "Distress / Festival Loan A/C", category: "asset", side: "Debit", visibility: "Confidential" },
  { code: "456", name: "Staff Welfare Membership Fee A/C", category: "liability", side: "Credit", visibility: "Standard" },
  { code: "458", name: "Uniform Issues & Recovery Control A/C", category: "asset", side: "Debit", visibility: "Store only" },
  { code: "459", name: "Insurance Recovery Collection A/C", category: "liability", side: "Credit", visibility: "Standard" },
  { code: "460", name: "Salaries Control (Payable Salaries) A/C", category: "liability", side: "Credit", visibility: "Confidential" },
  { code: "461", name: "EPF 20% Staff Contribution Payable A/C", category: "liability", side: "Credit", visibility: "Confidential" },
  { code: "462", name: "ETF 3% Employee Payable A/C", category: "liability", side: "Credit", visibility: "Confidential" },
  { code: "463", name: "Other Deductions Collection A/C", category: "liability", side: "Credit", visibility: "Confidential" },

  { code: "501", name: "Office Expenditure A/C", category: "operational_expense", side: "Debit", visibility: "Standard" },
  { code: "502", name: "Printing & Stationery Expenditure A/C", category: "operational_expense", side: "Debit", visibility: "Standard" },
  { code: "503", name: "Postage & Courier Expenditure A/C", category: "operational_expense", side: "Debit", visibility: "Standard" },
  { code: "504", name: "Traveling Subsistence Expenditure A/C", category: "operational_expense", side: "Debit", visibility: "Standard" },
  { code: "505", name: "Service Operation Expenditure A/C", category: "operational_expense", side: "Debit", visibility: "Standard" },
  { code: "506", name: "Vehicle Running & Maintenance Expenditure A/C", category: "operational_expense", side: "Debit", visibility: "Standard" },
  { code: "507", name: "Security Items (Torch / Umbrella) Expenditure A/C", category: "operational_expense", side: "Debit", visibility: "Store only" },
  { code: "508", name: "Cleaning Items & Materials Expenditure A/C", category: "operational_expense", side: "Debit", visibility: "Store only" },
  { code: "509", name: "Training, Permit, Licence & Miscellaneous A/C", category: "operational_expense", side: "Debit", visibility: "Standard" },
  { code: "510", name: "Tender Documents Expenditure A/C", category: "operational_expense", side: "Debit", visibility: "Standard" },
  { code: "511", name: "Refundable Tender Deposits A/C", category: "asset", side: "Debit", visibility: "Standard" },
  { code: "513", name: "Charity & Donation Expenditure A/C", category: "operational_expense", side: "Debit", visibility: "Standard" },
  { code: "514", name: "Marketing, Promotion, Subscription & Periodicals A/C", category: "operational_expense", side: "Debit", visibility: "Standard" },
  { code: "515", name: "Professional Fees Expenditure A/C", category: "operational_expense", side: "Debit", visibility: "Standard" },
  { code: "516", name: "Gratuity, Staff Training & Programme Expenditure A/C", category: "operational_expense", side: "Debit", visibility: "Standard" },
  { code: "517", name: "Petty Cash Control A/C", category: "asset", side: "Debit", visibility: "Standard" },
  { code: "518", name: "Managing Director's Current A/C", category: "liability", side: "Credit", visibility: "Confidential" },
  { code: "519", name: "Managing Director's Personal A/C", category: "asset", side: "Debit", visibility: "Confidential" },
  { code: "520", name: "Cleaning Service Other Expenditure A/C", category: "operational_expense", side: "Debit", visibility: "Standard" },
  { code: "551", name: "Security Points Control A/C", category: "operational_expense", side: "Debit", visibility: "Store only" },
  { code: "552", name: "Electricity Charges Expenditure A/C", category: "operational_expense", side: "Debit", visibility: "Standard" },
  { code: "553", name: "Water Supply Charges Expenditure A/C", category: "operational_expense", side: "Debit", visibility: "Standard" },
  { code: "554", name: "Telephone & Internet Charges Expenditure A/C", category: "operational_expense", side: "Debit", visibility: "Standard" },
  { code: "555", name: "Accruals & Accrued Creditors A/C", category: "liability", side: "Credit", visibility: "Admin only" },
  { code: "557", name: "Prepayment A/C (Advance Payment)", category: "asset", side: "Debit", visibility: "Admin only" },

  { code: "601", name: "Sundry Debtors A/C", category: "asset", side: "Debit", visibility: "Admin only" },
  { code: "602", name: "K.Y.S. Auto Service Main. & Exp. A/C", category: "property_expense", side: "Debit", visibility: "Standard" },
  { code: "603", name: "Pinarawa Housing Complex Main. & Exp. A/C", category: "property_expense", side: "Debit", visibility: "Standard" },
  { code: "604", name: "Welekade / Ratwatta Guest Main. & Exp. A/C", category: "property_expense", side: "Debit", visibility: "Standard" },
  { code: "605", name: "2nd Mile Post Shops / Chandrasiri House Main. & Exp. A/C", category: "property_expense", side: "Debit", visibility: "Standard" },
  { code: "606", name: "MD Home Upper Stairs / Fruit Shop Main. & Exp. A/C", category: "property_expense", side: "Debit", visibility: "Confidential" },
  { code: "607", name: "Velayudam Property Maintenance A/C", category: "property_expense", side: "Debit", visibility: "Standard" },
  { code: "608", name: "WIP – Velayudam Property Construction Phase I", category: "capital", side: "Debit", visibility: "Standard" },
  { code: "609", name: "MD House Expenditure A/C", category: "property_expense", side: "Debit", visibility: "Confidential" },
  { code: "610", name: "St. Bernard's Plantation A/C", category: "capital", side: "Debit", visibility: "Standard" },
  { code: "611", name: "Vineethagama House Main. & Exp. A/C", category: "property_expense", side: "Debit", visibility: "Standard" },
  { code: "612", name: "Kottawa Prime Residence Expenditure A/C", category: "property_expense", side: "Debit", visibility: "Confidential" },
  { code: "613", name: "Nilwala Hostel Main. & Expenditure A/C", category: "property_expense", side: "Debit", visibility: "Standard" },
  { code: "616", name: "Galaxy Hostel A&E Main. & Exp. A/C", category: "property_expense", side: "Debit", visibility: "Standard" },
  { code: "617", name: "SSC Levy Expenses Provision A/C", category: "liability", side: "Credit", visibility: "Admin only" },
  { code: "620", name: "WIP – Velayudam Property Construction Phase II", category: "capital", side: "Debit", visibility: "Standard" },
  { code: "630", name: "Pihillakade House Expenditure A/C", category: "capital", side: "Debit", visibility: "Standard" },
  { code: "632", name: "2nd Mile Post Co-operative Society Building Project", category: "capital", side: "Debit", visibility: "Standard" },
  { code: "635", name: "Pepper Cultivation Block – Kandana", category: "capital", side: "Debit", visibility: "Standard" },
  { code: "649", name: "WHT Recoverable A/C", category: "asset", side: "Debit", visibility: "Admin only" },
  { code: "650", name: "Security Contribution Levy A/C", category: "liability", side: "Credit", visibility: "Admin only" },
  { code: "651", name: "VAT Control A/C", category: "liability", side: "Credit", visibility: "Admin only" },
  { code: "652", name: "Personal Insurance Premium Expenditure A/C", category: "operational_expense", side: "Debit", visibility: "Confidential" },
  { code: "653", name: "Employees' Insurance Premium Expenditure A/C", category: "operational_expense", side: "Debit", visibility: "Standard" },
  { code: "654", name: "Vehicle & General Insurance Premium Expenditure A/C", category: "operational_expense", side: "Debit", visibility: "Standard" },
  { code: "655", name: "Financial / Loan & OD Interest Expenditure A/C", category: "operational_expense", side: "Debit", visibility: "Confidential" },
  { code: "658", name: "Chamber of Commerce & Industry Current A/C", category: "liability", side: "Credit", visibility: "Admin only" },
  { code: "660", name: "Sthawara Welfare Society Current A/C", category: "liability", side: "Credit", visibility: "Admin only" },
  { code: "661", name: "3rd Mile Post Building Construction A/C", category: "capital", side: "Debit", visibility: "Standard" },
  { code: "662", name: "St. Bernard Land Development A/C", category: "capital", side: "Debit", visibility: "Standard" },

  { code: "751", name: "Trade Debtors – Security Service Invoice O/S", category: "asset", side: "Debit", visibility: "Admin only" },
  { code: "752", name: "Trade Debtors – Security Service Invoice (Current Year)", category: "asset", side: "Debit", visibility: "Admin only" },
  { code: "753", name: "Trade Debtors – Cleaning Service Invoice O/S", category: "asset", side: "Debit", visibility: "Admin only" },
  { code: "754", name: "Trade Debtors – K.Y.S. Auto Service Rent O/S", category: "asset", side: "Debit", visibility: "Admin only" },
  { code: "755", name: "Sundry Debtors – Pinarawa Housing Rent O/S", category: "asset", side: "Debit", visibility: "Admin only" },
  { code: "756", name: "Sundry Debtors – Welekade / Ratwatta Guest Rent O/S", category: "asset", side: "Debit", visibility: "Admin only" },
  { code: "757", name: "Sundry Debtors – 2nd Mile Post Shops Rent O/S", category: "asset", side: "Debit", visibility: "Admin only" },
  { code: "758", name: "Sundry Debtors – MD Home Upper Stairs / Fruit Shop Rent O/S", category: "asset", side: "Debit", visibility: "Confidential" },
  { code: "759", name: "Sundry Debtors – Buddika / Ratwatta Guest O/S", category: "asset", side: "Debit", visibility: "Admin only" },
  { code: "760", name: "Sundry Debtors – Nilwala Hostel O/S", category: "asset", side: "Debit", visibility: "Admin only" },
  { code: "761", name: "Sundry Debtors – Galaxy Hostel O/S", category: "asset", side: "Debit", visibility: "Admin only" },
  { code: "762", name: "Personal Debtors – Mr. Waththagedara O/S", category: "asset", side: "Debit", visibility: "Confidential" },
  { code: "763", name: "Personal Debtors – Mr. Chathuranga O/S", category: "asset", side: "Debit", visibility: "Confidential" },
  { code: "764", name: "Personal Debtors – Mrs. Janki (Geththama)", category: "asset", side: "Debit", visibility: "Confidential" },
  { code: "765", name: "Sundry Debtors – Pihillakade Housing Complex Rent O/S", category: "asset", side: "Debit", visibility: "Admin only" },
  { code: "766", name: "Sundry Debtors – Vineethagama House Complex Rent O/S", category: "asset", side: "Debit", visibility: "Admin only" },
  { code: "767", name: "Trade Debtors – Security Service Invoice 2026", category: "asset", side: "Debit", visibility: "Admin only" },
  { code: "768", name: "Trade Debtors – Cleaning Service Invoice 2026", category: "asset", side: "Debit", visibility: "Admin only" },

  { code: "805", name: "Site Stocks – Chemicals & Equipment A/C", category: "asset", side: "Debit", visibility: "Store only" },
  { code: "806", name: "Uniform Office Stocks A/C", category: "asset", side: "Debit", visibility: "Store only" },
  { code: "807", name: "Cleaning Equipment Office Stocks A/C", category: "asset", side: "Debit", visibility: "Store only" },
  { code: "808", name: "Security Items Office Stocks A/C", category: "asset", side: "Debit", visibility: "Store only" },
  { code: "809", name: "Cleaning Items Office Stocks A/C", category: "asset", side: "Debit", visibility: "Store only" },
  { code: "810", name: "Material Purchase Suspense A/C", category: "asset", side: "Debit", visibility: "Admin only" },
  { code: "901", name: "Creditors Unidentified A/C", category: "liability", side: "Credit", visibility: "Admin only" },
  { code: "903", name: "Retained Net Profit A/C", category: "equity", side: "Credit", visibility: "Confidential" },
  { code: "904", name: "Previous Year (Profit Declared) P&L Adjustment A/C", category: "equity", side: "Credit", visibility: "Confidential" },
  { code: "905", name: "IRD Advance Payment (2025/2026)", category: "asset", side: "Debit", visibility: "Confidential" },
  { code: "906", name: "IRD Advance Payment (M/s K.Y.S. Pvt Ltd 2025/2026)", category: "asset", side: "Debit", visibility: "Confidential" },
  { code: "908", name: "IRD Advance Payment (2026/2027)", category: "asset", side: "Debit", visibility: "Confidential" },
  { code: "909", name: "IRD Advance Payment (M/s K.Y.S. Pvt Ltd 2026/2027)", category: "asset", side: "Debit", visibility: "Confidential" },
  { code: "910", name: "Tax Payable (Outstanding Tax up to 2024/2025)", category: "liability", side: "Credit", visibility: "Confidential" },
  { code: "911", name: "Profit & Loss A/C 2026", category: "equity", side: "Credit", visibility: "Confidential" },
];
